name: Go CI
permissions:
  contents: read
  security-events: write

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test on Go ${{ matrix.go-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.24' ]
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 2

      - name: Set up Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install Go tools
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
          go install github.com/mattn/goveralls@latest

      - name: Download Go modules
        run: |
          go mod download
          go mod verify

      - name: Run govulncheck
        uses: golang/govulncheck-action@b625fbe08f3bccbe446d94fbf87fcc875a4f50ee # v1.0.4

      - name: Lint source
        run: golangci-lint run ./...

      - name: Build loom executable (instrumented for coverage)
        run: go build -cover -o build/loom ./cmd/loom

      - name: Run tests and collect coverage
        env:
          GOCOVERDIR: ${{ github.workspace }}/coverage_data_e2e
        run: |
          mkdir -p ${{ github.workspace }}/coverage_data_e2e
          # Unit/integration tests contribute to unit_integration_coverage.out.
          # E2E tests running the instrumented 'build/loom' will have coverage data go to GOCOVERDIR.
          go test -v ./... -race -coverprofile=unit_integration_coverage.out -covermode=atomic

      - name: Prepare combined coverage report
        run: |
          E2E_COV_OUT_TMP_FILE="${{ github.workspace }}/e2e_coverage.tmp.out"
          UNIT_INTEGRATION_COV_FILE="unit_integration_coverage.out"
          FINAL_COV_FILE="final_coverage.out"

          # Ensure E2E temp coverage file exists, even if empty, after attempting to generate it.
          # This handles cases where no e2e binary tests were run or they produced no coverage.
          (go tool covdata textfmt -i=${{ github.workspace }}/coverage_data_e2e -o=${E2E_COV_OUT_TMP_FILE} 2>/dev/null) || touch ${E2E_COV_OUT_TMP_FILE}

          # Start the final coverage file with a single mode line
          echo "mode: atomic" > ${FINAL_COV_FILE}

          # Append content of unit_integration_coverage.out, skipping its mode line if present
          if [ -s ${UNIT_INTEGRATION_COV_FILE} ]; then
            # sed '1{/^mode: /d;}' will output the whole file, deleting the first line only if it matches /^mode: /
            sed '1{/^mode: /d;}' ${UNIT_INTEGRATION_COV_FILE} >> ${FINAL_COV_FILE}
          fi

          # Append content of e2e_coverage.tmp.out, skipping its mode line if present
          if [ -s ${E2E_COV_OUT_TMP_FILE} ]; then
            sed '1{/^mode: /d;}' ${E2E_COV_OUT_TMP_FILE} >> ${FINAL_COV_FILE}
          fi

          rm -f ${E2E_COV_OUT_TMP_FILE}

      - name: Upload coverage to Coveralls
        if: matrix.go-version == '1.24' # Only upload from one Go version
        env:
          COVERALLS_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: |
          goveralls -coverprofile=final_coverage.out -service=github -repotoken $COVERALLS_TOKEN
